version: "3.5"
services:
#---------------------------------------------------------------------------#
# Medcat Service                                                            #
#---------------------------------------------------------------------------#
  medcat-service:
      container_name: medcat-service
      image: cogstacksystems/medcat-service
      env_file:
        - ../../cogstack-pipeline/medcat_service/envs/env_app
        - ../../cogstack-pipeline/medcat_service/envs/env_medcat
      volumes:
      - ../data/models/medmen/vocab.dat:/cat/models/vocab.dat:ro
      - ../data/models/medmen/cdb.dat:/cat/models/cdb.dat:ro
      - ../data/models/medmen/mc_status:/cat/models/mc_status:ro
      ports:
      - "5000:5000"
      network_mode: host

#---------------------------------------------------------------------------#
# Medcat Trainer                                                            #
#---------------------------------------------------------------------------#
  medcat-trainer:
    container_name: medcat-trainer
    hostname: medcat
    restart: always
    image: cogstacksystems/medcat-trainer:latest
    volumes:
      - api-media:/home/api/media
      - api-static:/home/api/static
      - api-db:/home/api/db
    expose:
      - "8000"
    env_file:
      - ../../cogstack-pipeline/medcat_trainer/envs/env
    command: /home/run.sh
    network_mode: host
  nginx:
    container_name: medcattrainer_nginx
    image: cogstacksystems/medcat-trainer-nginx:latest
    restart: always
    volumes:
      - api-media:/home/api/media
      - api-static:/home/api/static
    ports:
      - "8001:8000"
    depends_on:
      - medcat-trainer
    network_mode: host