version: "3.5"
services:

 elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    shm_size : 128mb
    restart: always
    # use this in case of vm.max_map_count errors, the /usr/local/bin/docker-entry.sh is taken from the DockerHub image of elasticsearch
    #entrypoint: "/bin/sh -c 'echo vm.max_map_count=262144 >> /etc/sysctl.conf   && /usr/local/bin/docker-entrypoint.sh' "
    environment:
      - cluster.name=cogstack-elastic-cluster
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=admin
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - ../../cogstack-pipeline/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-vol-1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: host
  volumes:
    lasticsearch-vol-1:
      driver: local