version: "3.5"
services:
#---------------------------------------------------------------------------#
# Elasticsearch cluster                                                     #
#---------------------------------------------------------------------------#
 elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    shm_size : 128mb
    restart: always
    environment:
      - cluster.name=docker-cluster
     # - ELASTIC_USER:"admin"
     # - ELASTIC_PASSWORD:"admin"
     # - bootstrap.memory_lock=true
     # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ../../elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: host