version: "3.5"
services:

 kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.0
    # image: amazon/opendistro-for-elasticsearch-kibana:1.12.0
    shm_size : 128mb
    restart: always
    environment:
      SERVER_NAME: kibana.server
      # edit the url to match your server
      ELASTICSEARCH_HOSTS: "http://127.0.0.1:9200" 
    volumes:
      - ../../cogstack-pipeline/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    network_mode: host