version: "3.5"
services:
#---------------------------------------------------------------------------#
# Medcat Trainer                                                            #
#---------------------------------------------------------------------------#
  medcat-trainer:
    container_name: medcat-trainer
    hostname: medcat
    restart: always
    image: cogstacksystems/medcat-trainer:latest
    volumes:
      - api-media:/home/api/media
      - api-static:/home/api/static
      - api-db:/home/api/db
    expose:
      - "8000"
    env_file:
      - ../../cogstack-pipeline/medcat_trainer/envs/env
    command: /home/run.sh
    network_mode: host
  nginx:
    container_name: medcattrainer_nginx
    image: cogstacksystems/medcat-trainer-nginx:latest
    restart: always
    volumes:
      - api-media:/home/api/media
      - api-static:/home/api/static
    ports:
      - "8001:8000"
    depends_on:
      - medcat-trainer
    network_mode: host